Step 3: Mobile meunu
leehaney254/leehaney254.github.io pull request #4
Opened 2022-11-15 12:23 UTC by leehaney254

## In this system 👍 
- Added a mobile menu
- Used JavaScript to toggle the menu
- Modified the readme.md file

2022-11-15 20:06 UTC, Gopxfs requested changes
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi @leehaney254 @solorics 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/l4JzhjVCQiWgeAOFa/giphy.gif">

## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Menu working as intended.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 20:06 UTC, Gopxfs commented on styles.css
> +}
Nice job with your menu functionality! Please make sure to follow the same design displayed in Figma 😉.
| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/202013504-93d26546-dbba-4ae8-b0ae-8db052fe0d6e.png)  | ![image](https://user-images.githubusercontent.com/42799579/202013542-58418b89-d1da-4409-bcb4-52a95f755fd6.png)  |

Kindly notice:
- The links should begin with a capital letter (Portfolio & Contact).
- In your project, it is misspelled "portolio" 😉
- In the original design, the lines under the name of the links are wider, with the name of the links starting after some spacing:
![image](https://user-images.githubusercontent.com/42799579/202014172-37bde0a1-10e6-49d0-9053-da6e38f4dcad.png)
- The close button ('X') has more spacing between itself and the right border:

| Figma design  | Your design |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/42799579/202014538-ebc3557c-9af1-4fcb-8a57-526b1154fd92.png)  | ![image](https://user-images.githubusercontent.com/42799579/202014553-9ca6b828-c620-4366-be6f-fff85b8fc7a2.png)  |

> Keep in mind that this project's goal is to improve your ability to follow design guidelines (imagine Microverse as a client requesting a website) 😉.

2022-11-16 06:37 UTC, leehaney254 commented
## Changes 💪 
**I have:**
- Capitalized the first letter of the links
- Changed the spelling of the Portfolio
- Created wider lines at the bottom
- Spaced the close button

2022-11-16 06:47 UTC, gemmen29 approved these changes
Hi @leehaney254, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions:
- [ ]  [OPTIONAL] Kindly use the JavaScript + HTML + CSS linter as per this [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/7_mobile_menu.md#:~:text=For%20this%20project%2C%20you%20should%20add%20the%20JavaScript%20%2B%20HTML%20%2B%20CSS%20linter.). Now the js linters is not running. You need to change the linters.yml file with the new one in order to run. This will mark as optional as the previous reviewer does not request it but in the upcoming project, the PR will mark as invalid.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-16 07:00 UTC, merged